# Generated by Django 3.1.7 on 2021-03-27 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensordatavalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sensordatavalue',
            name='sensordata',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
        migrations.DeleteModel(
            name='SensorDataValue',
        ),
    ]
