# Generated by Django 3.2.12 on 2022-02-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20220212_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorlocation',
            name='city_old',
        ),
        migrations.AddField(
            model_name='sensorlocation',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_location', to='back.city'),
        ),
    ]
