# Generated by Django 3.2.12 on 2022-02-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_factory_factorytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
