# Generated by Django 3.2.12 on 2022-02-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_auto_20220212_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
