# Generated by Django 3.2.12 on 2022-02-11 23:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_auto_20220212_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
