# Generated by Django 3.2.12 on 2022-02-12 00:02

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0012_remove_factory_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
