# Generated by Django 3.2.12 on 2022-02-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0018_auto_20220213_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='factory_type',
            field=models.CharField(blank=True, choices=[('zavod', 'Завод'), ('musorka', 'Мусорка'), ('tec', 'ТЭЦ'), ('pred', 'Предприятие'), ('other', '')], max_length=9, null=True),
        ),
    ]
