# Generated by Django 3.2.12 on 2022-02-13 00:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0019_factory_factory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
