# Generated by Django 3.2.12 on 2022-02-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0020_factory_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='location',
        ),
    ]
