# Generated by Django 3.2.12 on 2022-02-13 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_remove_factory_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factory',
            old_name='point',
            new_name='location',
        ),
    ]
