# Generated by Django 3.2.12 on 2022-02-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_rename_point_factory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
