# Generated by Django 3.2.12 on 2022-02-18 22:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0024_factory_polygon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='node',
            name='description_internal',
        ),
        migrations.RemoveField(
            model_name='node',
            name='exact_location',
        ),
        migrations.RemoveField(
            model_name='node',
            name='location',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='location',
        ),
        migrations.AddField(
            model_name='factory',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='factory',
            name='postalcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='factory',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='industry_in_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='mac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='oven_in_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='node',
            name='postalcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='traffic_in_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='signal',
            name='postalcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='street_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='back.city'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='SensorLocation',
        ),
    ]
