# Generated by Django 3.2.12 on 2022-02-18 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_auto_20220219_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node', to='back.city'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factory', to='back.city'),
        ),
        migrations.AlterField(
            model_name='node',
            name='industry_in_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='oven_in_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='sensor_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='traffic_in_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
